-- HR Attendance & Performance Analytics System — schema v2, PostgreSQL edition.
-- GENERATED by scripts/build_pg_schema.py from schema.sql (the source of truth). Do not edit by hand.
-- Differences from SQLite:
--   * INTEGER PRIMARY KEY          -> GENERATED BY DEFAULT AS IDENTITY
--   * REAL / BLOB                  -> DOUBLE PRECISION / BYTEA
--   * datetime('now') defaults     -> to_char(now(), ...)   (timestamps stay ISO TEXT, as in SQLite)
--   * foreign keys are added at the end, because departments and employees
--     reference each other and PostgreSQL has no forward references
-- Dates and times are ISO-8601 TEXT on purpose: the same queries and string
-- comparisons run unchanged on both engines. Power BI converts types on load.
-- Tested on PostgreSQL 16 and on Supabase. Safe to run more than once.

-- ---------------------------------------------------------------- org ----
CREATE TABLE IF NOT EXISTS departments (
    department_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 TEXT NOT NULL UNIQUE,
    name                 TEXT NOT NULL,
    name_ar              TEXT,                     -- v3: Arabic name (optional; English is used when empty)
    manager_employee_id  INTEGER,
    is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at           TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS shifts (
    shift_id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                       TEXT NOT NULL UNIQUE,
    name                       TEXT NOT NULL,
    name_ar                    TEXT,                   -- v3
    start_time                 TEXT NOT NULL,          -- 'HH:MM'
    end_time                   TEXT NOT NULL,          -- 'HH:MM'; end <= start means the shift crosses midnight
    grace_minutes              INTEGER NOT NULL DEFAULT 15 CHECK (grace_minutes BETWEEN 0 AND 120),
    early_leave_grace_minutes  INTEGER NOT NULL DEFAULT 5 CHECK (early_leave_grace_minutes BETWEEN 0 AND 120),
    workdays                   TEXT NOT NULL DEFAULT 'SUN,MON,TUE,WED,THU',
    is_active                  INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS employees (
    employee_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code        TEXT NOT NULL UNIQUE,
    badge_id             TEXT NOT NULL UNIQUE,     -- identifier used by the time-clock device
    full_name            TEXT NOT NULL,
    full_name_ar         TEXT,                     -- v3: Arabic spelling of the name
    gender               TEXT CHECK (gender IS NULL OR gender IN ('M', 'F')),  -- v3: for correct Arabic grammar
    email                TEXT UNIQUE,              -- also the Power BI UPN for RLS
    job_title            TEXT,
    job_title_ar         TEXT,                     -- v3
    department_id        INTEGER NOT NULL,
    manager_employee_id  INTEGER,
    hire_date            TEXT NOT NULL,
    termination_date     TEXT,
    is_synthetic         INTEGER NOT NULL DEFAULT 0,
    CHECK (termination_date IS NULL OR termination_date >= hire_date)
);
CREATE INDEX IF NOT EXISTS ix_employees_department ON employees(department_id);

CREATE TABLE IF NOT EXISTS employee_shift_assignments (
    assignment_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INTEGER NOT NULL,
    shift_id        INTEGER NOT NULL,
    effective_from  TEXT NOT NULL,
    effective_to    TEXT,                            -- inclusive; NULL = open-ended
    UNIQUE (employee_id, effective_from),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE IF NOT EXISTS holidays (
    holiday_date     TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    name_ar          TEXT,                         -- v3
    is_illustrative  INTEGER NOT NULL DEFAULT 0    -- 1 = approximate date, verify against the official calendar
);

CREATE TABLE IF NOT EXISTS leave_requests (
    leave_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id          INTEGER NOT NULL,
    leave_type           TEXT NOT NULL CHECK (leave_type IN ('annual', 'sick', 'unpaid', 'other')),
    start_date           TEXT NOT NULL,
    end_date             TEXT NOT NULL,
    status               TEXT NOT NULL CHECK (status IN ('approved', 'pending', 'rejected', 'cancelled')),
    approved_by_user_id  INTEGER,   -- the decider (approve OR reject)
    -- v2: self-service workflow (NULL for records entered directly by HR or loaded from files)
    reason               TEXT,
    requested_by_user_id INTEGER,
    requested_at         TEXT,
    decided_at           TEXT,
    decision_note        TEXT,
    CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS ix_leave_employee ON leave_requests(employee_id, start_date);
CREATE INDEX IF NOT EXISTS ix_leave_status ON leave_requests(status, employee_id);

-- -------------------------------------------------------------- users ----
CREATE TABLE IF NOT EXISTS users (
    user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('gm', 'hr', 'manager', 'employee')),  -- gm = General Manager (v3)
    employee_id    INTEGER UNIQUE,
    is_active      INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    last_login_at  TEXT,
    created_at     TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    must_change_password INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))  -- v2
);

-- ------------------------------------------------------------ imports ----
CREATE TABLE IF NOT EXISTS import_batches (
    batch_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type           TEXT NOT NULL,           -- 'csv' | 'excel'
    source_name           TEXT NOT NULL,           -- original file name
    stored_path           TEXT,                    -- copy kept for provenance
    source_device         TEXT,
    source_timezone       TEXT NOT NULL,
    file_sha256           TEXT NOT NULL,
    imported_by_user_id   INTEGER,
    imported_at           TEXT NOT NULL,
    status                TEXT NOT NULL CHECK (status IN ('success', 'partial', 'failed')),
    rows_total            INTEGER NOT NULL DEFAULT 0,
    rows_accepted         INTEGER NOT NULL DEFAULT 0,  -- new raw punches stored
    rows_duplicate        INTEGER NOT NULL DEFAULT 0,  -- valid but already stored
    rows_rejected         INTEGER NOT NULL DEFAULT 0,  -- quarantined in rejected_rows
    min_punch_time        TEXT,
    max_punch_time        TEXT,
    message               TEXT
);
-- the same file content can only be loaded successfully once
CREATE UNIQUE INDEX IF NOT EXISTS ux_import_file_once
    ON import_batches(file_sha256) WHERE status IN ('success', 'partial');

CREATE TABLE IF NOT EXISTS raw_punches (
    punch_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          INTEGER NOT NULL,
    source_row        INTEGER NOT NULL,            -- 1-based data row in the source file
    badge_id          TEXT NOT NULL,
    employee_id       INTEGER NOT NULL,
    punch_time_local  TEXT NOT NULL,               -- normalised to ORG_TIMEZONE
    punch_time_raw    TEXT NOT NULL,               -- exactly as received
    punch_type        TEXT NOT NULL DEFAULT 'UNKNOWN',  -- device-reported IN/OUT, informational only
    device_id         TEXT NOT NULL DEFAULT '',
    UNIQUE (employee_id, punch_time_local, device_id)
);
CREATE INDEX IF NOT EXISTS ix_raw_punches_emp_time ON raw_punches(employee_id, punch_time_local);

CREATE TABLE IF NOT EXISTS rejected_rows (
    reject_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id       INTEGER NOT NULL,
    source_row     INTEGER NOT NULL,
    raw_data       TEXT NOT NULL,                  -- JSON of the original row
    reason_code    TEXT NOT NULL,
    reason_detail  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_rejected_batch ON rejected_rows(batch_id);

-- ---------------------------------------------------- attendance output ----
CREATE TABLE IF NOT EXISTS attendance_daily (
    employee_id          INTEGER NOT NULL,
    shift_date           TEXT NOT NULL,            -- the date the shift STARTS on
    shift_id             INTEGER,
    scheduled_start      TEXT,
    scheduled_end        TEXT,
    scheduled_minutes    INTEGER,
    status               TEXT NOT NULL CHECK (status IN (
                            'present', 'incomplete', 'absent', 'leave', 'holiday',
                            'day_off', 'pending', 'unscheduled_work')),
    raw_punch_count      INTEGER NOT NULL DEFAULT 0,
    punch_count          INTEGER NOT NULL DEFAULT 0, -- after collapsing near-duplicates
    first_punch          TEXT,
    last_punch           TEXT,
    is_late              INTEGER NOT NULL DEFAULT 0,
    late_minutes         INTEGER NOT NULL DEFAULT 0,
    early_leave_minutes  INTEGER NOT NULL DEFAULT 0,
    span_minutes         INTEGER,                  -- last - first punch; NOT verified working time
    leave_type           TEXT,
    holiday_name         TEXT,
    notes                TEXT,
    rule_version         TEXT NOT NULL,
    processed_at         TEXT NOT NULL,
    PRIMARY KEY (employee_id, shift_date)
);
CREATE INDEX IF NOT EXISTS ix_attendance_date ON attendance_daily(shift_date);

CREATE TABLE IF NOT EXISTS punch_exceptions (
    punch_id          INTEGER PRIMARY KEY,
    employee_id       INTEGER NOT NULL,
    punch_time_local  TEXT NOT NULL,
    shift_date        TEXT,
    reason            TEXT NOT NULL CHECK (reason IN ('outside_employment', 'no_shift_window', 'no_shift_assignment')),
    detected_at       TEXT NOT NULL
);

-- -------------------------------------------------------- performance ----
CREATE TABLE IF NOT EXISTS evaluation_weights (
    weights_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_from      TEXT NOT NULL UNIQUE,      -- first period 'YYYY-MM' the weights apply to
    w_punctuality       DOUBLE PRECISION NOT NULL CHECK (w_punctuality BETWEEN 0 AND 100),
    w_communication     DOUBLE PRECISION NOT NULL CHECK (w_communication BETWEEN 0 AND 100),
    w_task_completion   DOUBLE PRECISION NOT NULL CHECK (w_task_completion BETWEEN 0 AND 100),
    w_teamwork          DOUBLE PRECISION NOT NULL CHECK (w_teamwork BETWEEN 0 AND 100),
    created_by_user_id  INTEGER,
    created_at          TEXT NOT NULL,
    CHECK (abs(w_punctuality + w_communication + w_task_completion + w_teamwork - 100) < 0.001)
);

CREATE TABLE IF NOT EXISTS performance_evaluations (
    evaluation_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id            INTEGER NOT NULL,
    period                 TEXT NOT NULL,          -- 'YYYY-MM'
    evaluator_user_id      INTEGER NOT NULL,
    score_punctuality      INTEGER NOT NULL CHECK (score_punctuality BETWEEN 1 AND 5),
    score_communication    INTEGER NOT NULL CHECK (score_communication BETWEEN 1 AND 5),
    score_task_completion  INTEGER NOT NULL CHECK (score_task_completion BETWEEN 1 AND 5),
    score_teamwork         INTEGER NOT NULL CHECK (score_teamwork BETWEEN 1 AND 5),
    weights_id             INTEGER NOT NULL,
    weighted_score         DOUBLE PRECISION NOT NULL CHECK (weighted_score BETWEEN 1 AND 5),
    comments               TEXT,
    created_at             TEXT NOT NULL,
    updated_at             TEXT NOT NULL,
    UNIQUE (employee_id, period)
);

CREATE TABLE IF NOT EXISTS evaluation_history (
    history_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id       INTEGER NOT NULL,
    changed_by_user_id  INTEGER NOT NULL,
    changed_at          TEXT NOT NULL,
    action              TEXT NOT NULL CHECK (action IN ('create', 'update')),
    old_values          TEXT,                      -- JSON
    new_values          TEXT NOT NULL              -- JSON
);

-- v2: employee-reported missed punches. An approved correction becomes a raw
-- punch in a 'manual' import batch (device_id 'MANUAL'), so it flows through
-- the normal rules and stays traceable to the request and the approver.
CREATE TABLE IF NOT EXISTS attendance_corrections (
    correction_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id           INTEGER NOT NULL,
    shift_date            TEXT NOT NULL,
    punch_time            TEXT NOT NULL,           -- 'YYYY-MM-DD HH:MM:SS' org-local
    punch_kind            TEXT NOT NULL CHECK (punch_kind IN ('in', 'out')),
    reason                TEXT NOT NULL,
    status                TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    requested_by_user_id  INTEGER NOT NULL,
    requested_at          TEXT NOT NULL,
    decided_by_user_id    INTEGER,
    decided_at            TEXT,
    decision_note         TEXT,
    punch_id              INTEGER
);
CREATE INDEX IF NOT EXISTS ix_corrections_status ON attendance_corrections(status, employee_id);

-- ------------------------------------------------------------- system ----
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TEXT NOT NULL,
    user_id      INTEGER,
    action       TEXT NOT NULL,
    entity       TEXT NOT NULL,
    entity_id    TEXT,
    details      TEXT,                              -- JSON
    remote_addr  TEXT
);
CREATE INDEX IF NOT EXISTS ix_audit_time ON audit_log(occurred_at);

CREATE TABLE IF NOT EXISTS report_runs (
    run_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type   TEXT NOT NULL,
    period        TEXT NOT NULL,
    scope_key     TEXT NOT NULL,                    -- 'org' or 'dept:<id>'
    status        TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'superseded')),
    triggered_by  TEXT NOT NULL,
    started_at    TEXT NOT NULL,
    finished_at   TEXT,
    output_path   TEXT,
    error         TEXT
);
-- at most one running-or-successful run per report/period/scope (prevents accidental duplicates)
CREATE UNIQUE INDEX IF NOT EXISTS ux_report_once
    ON report_runs(report_type, period, scope_key) WHERE status IN ('running', 'success');

CREATE TABLE IF NOT EXISTS risk_scores (
    employee_id     INTEGER NOT NULL,
    feature_period  TEXT NOT NULL,
    target_period   TEXT NOT NULL,
    probability     DOUBLE PRECISION NOT NULL,
    method          TEXT NOT NULL CHECK (method IN ('model', 'rules')),
    model_version   TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    PRIMARY KEY (employee_id, target_period, model_version)
);

-- v2: generated files (model evaluation, PDF reports) kept in the database as well
-- as on disk, so a host with a temporary filesystem (e.g. a free cloud web
-- service) still serves them after a restart.
CREATE TABLE IF NOT EXISTS stored_files (
    path          TEXT PRIMARY KEY,                -- logical name, e.g. 'reports/hr_monthly_2026-08_org_run1.pdf'
    content       BYTEA NOT NULL,
    content_type  TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_meta (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);
-- Fresh databases start at the current version; older ones are upgraded by
-- db/connection.py:migrate() (called by init-db and on web start-up).
INSERT INTO schema_meta(key, value) VALUES ('schema_version', '3') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------- foreign keys ----
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_departments_manager_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE departments ADD CONSTRAINT fk_departments_manager_employee_id FOREIGN KEY (manager_employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employees_department_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE employees ADD CONSTRAINT fk_employees_department_id FOREIGN KEY (department_id) REFERENCES departments(department_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employees_manager_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE employees ADD CONSTRAINT fk_employees_manager_employee_id FOREIGN KEY (manager_employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employee_shift_assignments_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE employee_shift_assignments ADD CONSTRAINT fk_employee_shift_assignments_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employee_shift_assignments_shift_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE employee_shift_assignments ADD CONSTRAINT fk_employee_shift_assignments_shift_id FOREIGN KEY (shift_id) REFERENCES shifts(shift_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE leave_requests ADD CONSTRAINT fk_leave_requests_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_approved_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE leave_requests ADD CONSTRAINT fk_leave_requests_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_requested_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE leave_requests ADD CONSTRAINT fk_leave_requests_requested_by_user_id FOREIGN KEY (requested_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE users ADD CONSTRAINT fk_users_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_import_batches_imported_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE import_batches ADD CONSTRAINT fk_import_batches_imported_by_user_id FOREIGN KEY (imported_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_raw_punches_batch_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE raw_punches ADD CONSTRAINT fk_raw_punches_batch_id FOREIGN KEY (batch_id) REFERENCES import_batches(batch_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_raw_punches_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE raw_punches ADD CONSTRAINT fk_raw_punches_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rejected_rows_batch_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE rejected_rows ADD CONSTRAINT fk_rejected_rows_batch_id FOREIGN KEY (batch_id) REFERENCES import_batches(batch_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_daily_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_daily ADD CONSTRAINT fk_attendance_daily_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_daily_shift_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_daily ADD CONSTRAINT fk_attendance_daily_shift_id FOREIGN KEY (shift_id) REFERENCES shifts(shift_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_punch_exceptions_punch_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE punch_exceptions ADD CONSTRAINT fk_punch_exceptions_punch_id FOREIGN KEY (punch_id) REFERENCES raw_punches(punch_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evaluation_weights_created_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE evaluation_weights ADD CONSTRAINT fk_evaluation_weights_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_performance_evaluations_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE performance_evaluations ADD CONSTRAINT fk_performance_evaluations_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_performance_evaluations_evaluator_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE performance_evaluations ADD CONSTRAINT fk_performance_evaluations_evaluator_user_id FOREIGN KEY (evaluator_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_performance_evaluations_weights_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE performance_evaluations ADD CONSTRAINT fk_performance_evaluations_weights_id FOREIGN KEY (weights_id) REFERENCES evaluation_weights(weights_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evaluation_history_evaluation_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE evaluation_history ADD CONSTRAINT fk_evaluation_history_evaluation_id FOREIGN KEY (evaluation_id) REFERENCES performance_evaluations(evaluation_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evaluation_history_changed_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE evaluation_history ADD CONSTRAINT fk_evaluation_history_changed_by_user_id FOREIGN KEY (changed_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_corrections_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_corrections ADD CONSTRAINT fk_attendance_corrections_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_corrections_requested_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_corrections ADD CONSTRAINT fk_attendance_corrections_requested_by_user_id FOREIGN KEY (requested_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_corrections_decided_by_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_corrections ADD CONSTRAINT fk_attendance_corrections_decided_by_user_id FOREIGN KEY (decided_by_user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_corrections_punch_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE attendance_corrections ADD CONSTRAINT fk_attendance_corrections_punch_id FOREIGN KEY (punch_id) REFERENCES raw_punches(punch_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_log_user_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE audit_log ADD CONSTRAINT fk_audit_log_user_id FOREIGN KEY (user_id) REFERENCES users(user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_risk_scores_employee_id' AND connamespace = current_schema()::regnamespace) THEN
    ALTER TABLE risk_scores ADD CONSTRAINT fk_risk_scores_employee_id FOREIGN KEY (employee_id) REFERENCES employees(employee_id);
  END IF;
END $$;
