"""Regenerate hr_analytics/db/schema_postgres.sql from the SQLite schema.

    python scripts/build_pg_schema.py

schema.sql is the source of truth. Run this after changing it; the test
tests/test_postgres_schema.py fails if the two files disagree.
"""
from __future__ import annotations

import re
from pathlib import Path

DB = Path(__file__).resolve().parent.parent / "hr_analytics" / "db"

HEADER = """-- HR Attendance & Performance Analytics System — schema v2, PostgreSQL edition.
-- GENERATED by scripts/build_pg_schema.py from schema.sql (the source of truth). Do not edit by hand.
-- Differences from SQLite:
--   * INTEGER PRIMARY KEY          -> GENERATED BY DEFAULT AS IDENTITY
--   * REAL / BLOB                  -> DOUBLE PRECISION / BYTEA
--   * datetime('now') defaults     -> to_char(now(), ...)   (timestamps stay ISO TEXT, as in SQLite)
--   * foreign keys are added at the end, because departments and employees
--     reference each other and PostgreSQL has no forward references
-- Dates and times are ISO-8601 TEXT on purpose: the same queries and string
-- comparisons run unchanged on both engines. Power BI converts types on load.
-- Tested on PostgreSQL 16 and on Supabase. Safe to run more than once.

"""


def build(src: str) -> str:
    out, fks, table = [], [], None
    for line in src.splitlines():
        if line.startswith("PRAGMA"):
            continue
        m = re.match(r"CREATE TABLE IF NOT EXISTS (\w+)", line)
        if m:
            table = m.group(1)
        line = re.sub(r"^(\s+\w+\s+)INTEGER PRIMARY KEY,", r"\1INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,", line)
        fm = re.match(r"^(\s+)(\w+)(\s+.*?)\s+REFERENCES (\w+)\((\w+)\)(.*)$", line)
        if fm and table:
            col, ref_t, ref_c = fm.group(2), fm.group(4), fm.group(5)
            fks.append((f"fk_{table}_{col}", f"ALTER TABLE {table} ADD CONSTRAINT fk_{table}_{col} "
                                              f"FOREIGN KEY ({col}) REFERENCES {ref_t}({ref_c});"))
            line = f"{fm.group(1)}{col}{fm.group(3)}{fm.group(6)}"
        line = re.sub(r"\bREAL\b", "DOUBLE PRECISION", line)
        line = re.sub(r"\bBLOB\b", "BYTEA", line)
        line = line.replace("DEFAULT (datetime('now'))", "DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))")
        line = re.sub(r"INSERT OR IGNORE INTO (.*);$", r"INSERT INTO \1 ON CONFLICT DO NOTHING;", line)
        out.append(line)
    body = re.sub(r"^-- HR Attendance.*?\n\n", "", "\n".join(out), count=1, flags=re.S).strip()
    fk_sql = "\n".join(f"  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{name}' "
                       f"AND connamespace = current_schema()::regnamespace) THEN\n    {stmt}\n  END IF;"
                       for name, stmt in fks)
    return (HEADER + body + "\n\n-- ---------------------------------------------------------- foreign keys ----\n"
            "DO $$\nBEGIN\n" + fk_sql + "\nEND $$;\n")


if __name__ == "__main__":
    text = build((DB / "schema.sql").read_text(encoding="utf-8"))
    (DB / "schema_postgres.sql").write_text(text, encoding="utf-8")
    print(f"wrote {DB / 'schema_postgres.sql'}")
